repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        types_or: [python]
      # Run the formatter.
      - id: ruff-format
        args: [ "--config", "format.line-ending = \"lf\"" ]
        types_or: [python]
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      # Format, organize imports, lint, and apply safe fixes to the committed files
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        types_or: [javascript, jsx, ts, tsx, css, json]
